import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-app.js';
import {
  getFirestore,
  collection,
  addDoc,
  onSnapshot,
  updateDoc,
  doc,
} from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-firestore.js';
import config from './config';
import { getFormatCurrency } from '../utility/currencychange';

// Initialize Firebase
const app = initializeApp(config);

const db = getFirestore(app);

// let transactions = {
//   data: [
//     {
//       fecha: '01-01-2022 22:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Proveedores',
//       monto: '200000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Transferencias a Terceros',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Boleta de Garantia',
//       monto: '100',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Previred',
//       monto: '10',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Impuestos',
//       monto: '1',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Remuneraciones',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Proveedores',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Transferencias a Terceros',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '262925378',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Boleta de Garantia',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Remuneraciones',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Proveedores',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Transferencias a Terceros',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Boleta de Garantia',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Proveedores',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Transferencias a Terceros',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Boleta de Garantia',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Remuneraciones',
//       monto: '50000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Proveedores',
//       monto: '10000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Transferencias a Terceros',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Boleta de Garantia',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Previred',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Impuestos',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Remuneraciones',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Proveedores',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Transferencias a Terceros',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Boleta de Garantia',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Previred',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Impuestos',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '10000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//   ],
// };

// let movements = {
//   data: [
//     {
//       fecha: '01/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '04/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '05/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '07/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '08/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '09/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '10/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '11/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/01/2022',
//       codigomovimiento: '11',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '2000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/02/2022',
//       codigomovimiento: '762',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '1000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/03/2022',
//       codigomovimiento: '981',
//       descripcion: 'ABONO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '5000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/04/2022',
//       codigomovimiento: '983',
//       descripcion: 'ABONO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '10000000000',
//       cargo: '',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/05/2022',
//       codigomovimiento: '10',
//       descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '3000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/06/2022',
//       codigomovimiento: '703',
//       descripcion: 'PAGO PREVIRED',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '1',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/07/2022',
//       codigomovimiento: '761',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '100',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/08/2022',
//       codigomovimiento: '837',
//       descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '500000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/09/2022',
//       codigomovimiento: '861',
//       descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '7000000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/10/2022',
//       codigomovimiento: '982',
//       descripcion: 'CARGO MANUAL DE COMEX',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '2765987',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '12/11/2022',
//       codigomovimiento: '987',
//       descripcion: 'CARGO TRANSFERENCIA SPAV',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '300000000',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01/01/2022',
//       codigomovimiento: '123',
//       descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       sucursal: 'Operaciones Web',
//       abono: '10000000',
//       cargo: '',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '02/01/2022',
//       codigomovimiento: '124',
//       descripcion: 'ABONO PAGO DE PROVEEDORES',
//       sucursal: 'Operaciones Web',
//       abono: '',
//       cargo: '10000000',
//       currencycode: 'USD',
//     },
//   ],
// };

// let companies = {
//   data: [
//     {
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       'Cuenta Corriente': [
//         { numerocta: '210456783', tipocta: 'Cuenta Pesos' },
//         { numerocta: '217683922', tipocta: 'Cuenta Pesos' },
//         { numerocta: '229875367', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//     {
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       'Cuenta Corriente': [
//         { numerocta: '236748967', tipocta: 'Cuenta Pesos' },
//         { numerocta: '214536278', tipocta: 'Cuenta Pesos' },
//         { numerocta: '237849567', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//     {
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       'Cuenta Corriente': [
//         { numerocta: '223987454', tipocta: 'Cuenta Pesos' },
//         { numerocta: '223764839', tipocta: 'Cuenta Pesos' },
//         { numerocta: '211235678', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//     {
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       'Cuenta Corriente': [
//         { numerocta: '229435678', tipocta: 'Cuenta Pesos' },
//         { numerocta: '220674598', tipocta: 'Cuenta Pesos' },
//         { numerocta: '226354968', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//     {
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       'Cuenta Corriente': [
//         { numerocta: '215364789', tipocta: 'Cuenta Pesos' },
//         { numerocta: '126473890', tipocta: 'Cuenta Pesos' },
//         { numerocta: '223647891', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//     {
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       'Cuenta Corriente': [
//         { numerocta: '362925378', tipocta: 'Cuenta Dolar' },
//         { numerocta: '224637807', tipocta: 'Cuenta Pesos' },
//         { numerocta: '223564738', tipocta: 'Cuenta Pesos' },
//       ],
//     },
//   ],
// };

// export const dataset = companies.data.forEach(function (obj) {
//   const postId = Math.random().toString(16).slice(2);
//   addDoc(collection(db, 'companies'), {
//     id: postId,
//     rut: obj.Rut,
//     'Razon Social': obj['Razon Social'],
//     segment: obj.Segmento,
//     accounts: obj['Cuenta Corriente'],
//     // payment: obj.abono
//     //   ? `${obj.currencycode} ${getFormatCurrency(obj.abono, obj.currencycode)}`
//     //   : '-',
//     // charge: obj.cargo
//     //   ? `${obj.currencycode} ${getFormatCurrency(obj.cargo, obj.currencycode)}`
//     //   : '-',
//   })
//     .then(function (docRef) {
//       console.log('Document written with ID: ', docRef.id);
//     })
//     .catch(function (error) {
//       console.error('Error adding document: ', error);
//     });
// });

export { app, db, collection, onSnapshot, updateDoc, doc };
