import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-app.js';
import {
  getFirestore,
  collection,
  addDoc,
  onSnapshot,
  updateDoc,
  doc,
} from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-firestore.js';
import { getAuth } from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-auth.js';
import config from './config';
import { getFormatCurrency } from '../utility/currencychange';

// Initialize Firebase
const app = initializeApp(config);

const db = getFirestore(app);
const auth = getAuth();

// let transactions = {
//   data: [

//   ],
// };

// let movements = {
//   data: [
//     {
//       'Fecha y Hora': '01/01/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/02/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/03/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/04/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/05/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/06/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/07/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/08/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '210456783',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/09/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/10/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/11/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/01/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/02/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/03/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/04/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '217683922',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/05/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/06/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/07/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/08/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/09/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/10/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '02/11/2022',
//       Rut: '76.894.657-5',
//       'Razon Social': 'MegaHold Prime',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '229875367',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/01/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/02/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/03/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/04/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/05/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/06/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/07/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '236748967',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/08/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/09/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/10/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '03/11/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/01/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/02/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/03/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '214536278',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/04/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/05/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/06/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/07/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/08/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/09/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/10/2022',
//       Rut: '90.123.567-0',
//       'Razon Social': 'Inmobiliaria Velasco',
//       Segmento: 'Inmobiliaria',
//       Cuenta: '237849567',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '04/11/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/01/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/02/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/03/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/04/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/05/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/06/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223987454',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/07/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/08/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/09/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/10/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '05/11/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/01/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/02/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '223764839',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/03/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/04/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/05/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/06/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/07/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/08/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/09/2022',
//       Rut: '77.879.456-9',
//       'Razon Social': 'Inversiones Hacktahon',
//       Segmento: 'Grandes Empresas',
//       Cuenta: '211235678',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/10/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '06/11/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/01/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/02/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/03/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/04/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/05/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '229435678',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/06/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/07/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/08/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/09/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/10/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '07/11/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/01/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '220674598',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/02/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/03/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/04/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/05/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/06/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/07/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/08/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/09/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/10/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '08/11/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/01/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/02/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/03/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/04/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/05/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/06/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/07/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/08/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/09/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/10/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '09/11/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '126473890',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/01/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/02/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/03/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/04/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/05/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/06/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/07/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/08/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/09/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/10/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '10/11/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/01/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/02/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/03/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/04/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/05/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/06/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/07/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/08/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/09/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/10/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '11/11/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/01/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '11',
//       Descripcion: 'ABONO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '2000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/02/2022',
//       Rut: '95.476.897-1',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '223564738',
//       'Codigo Movimiento': '762',
//       Descripcion: 'ABONO PAGO DE PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '1000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/03/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '981',
//       Descripcion: 'ABONO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '5000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/04/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '224637807',
//       'Codigo Movimiento': '983',
//       Descripcion: 'ABONO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000000',
//       Cargo: '',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/05/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '10',
//       Descripcion: 'CARGO TRANSFERENCIA INTERNET',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '3000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/06/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '223647891',
//       'Codigo Movimiento': '703',
//       Descripcion: 'PAGO PREVIRED',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '1',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/07/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '761',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '100',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/08/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '837',
//       Descripcion: 'PAGO EFECTUADO A PROVEEDORES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '500000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/09/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Inversiones Latinoamericanas',
//       Segmento: 'Multinacionales',
//       Cuenta: '226354968',
//       'Codigo Movimiento': '861',
//       Descripcion: 'CARGO PAGO DE REMUNERACIONES H2H',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '7000000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/10/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '982',
//       Descripcion: 'CARGO MANUAL DE COMEX',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '2765987',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '12/11/2022',
//       Rut: '81.345.789-0',
//       'Razon Social': 'Supermercados Grupo 44',
//       Segmento: 'Corporate Invesment Banking',
//       Cuenta: '215364789',
//       'Codigo Movimiento': '987',
//       Descripcion: 'CARGO TRANSFERENCIA SPAV',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '300000000',
//       Currencycode: 'CLP',
//     },
//     {
//       'Fecha y Hora': '01/01/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '362925378',
//       'Codigo Movimiento': '123',
//       Descripcion: 'COMPRA DOLARES',
//       Sucursal: 'Operaciones Web',
//       Abono: '10000000',
//       Cargo: '2765987',
//       Currencycode: 'USD',
//     },
//     {
//       'Fecha y Hora': '01/02/2022',
//       Rut: '61.145.789-0',
//       'Razon Social': 'Universidades Americanas',
//       Segmento: 'Institucionales',
//       Cuenta: '362925378',
//       'Codigo Movimiento': '124',
//       Descripcion: 'VENTA DOLARES',
//       Sucursal: 'Operaciones Web',
//       Abono: '',
//       Cargo: '10000000',
//       Currencycode: 'USD',
//     },
//   ],
// };

// // let companies = {
// //   data: [],
// // };

// export const dataset = movements.data.forEach(function (obj) {
//   const postId = Math.random().toString(16).slice(2);
//   addDoc(collection(db, 'movements'), {
//     id: postId,
//     date: obj['Fecha y Hora'],
//     rut: obj.Rut,
//     ['Razon Social']: obj['Razon Social'],
//     segment: obj.Segmento,
//     account: obj.Cuenta,
//     codemov: obj['Codigo Movimiento'],
//     description: obj.Descripcion,
//     branch: obj.Sucursal,
//     payment: obj.Abono
//       ? `${obj.Currencycode} ${getFormatCurrency(obj.Abono, obj.Currencycode)}`
//       : '-',
//     charge: obj.Cargo
//       ? `${obj.Currencycode} ${getFormatCurrency(obj.Cargo, obj.Currencycode)}`
//       : '-',
//   })
//     .then(function (docRef) {
//       console.log('Document written with ID: ', docRef.id);
//     })
//     .catch(function (error) {
//       console.error('Error adding document: ', error);
//     });
// });

export { app, db, collection, onSnapshot, updateDoc, doc };
