import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-app.js';
import {
  getFirestore,
  collection,
  addDoc,
  onSnapshot,
} from 'https://www.gstatic.com/firebasejs/9.9.3/firebase-firestore.js';
import config from './config';
import { getFormatCurrency } from '../utility/currencychange';

// Initialize Firebase
const app = initializeApp(config);

const db = getFirestore(app);

// let transactions = {
//   data: [
//     {
//       fecha: '01-01-2022 22:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Proveedores',
//       monto: '200000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Transferencias a Terceros',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Boleta de Garantia',
//       monto: '100',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Previred',
//       monto: '10',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Impuestos',
//       monto: '1',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Remuneraciones',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Proveedores',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Transferencias a Terceros',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '262925378',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Boleta de Garantia',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '3000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Remuneraciones',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Proveedores',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Transferencias a Terceros',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Boleta de Garantia',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Proveedores',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Transferencias a Terceros',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Boleta de Garantia',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-01-2022 08:33 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Previred',
//       monto: '450000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Impuestos Dolares',
//       monto: '10000000',
//       estado: 'pendiente',
//       currencycode: 'USD',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '700000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Remuneraciones',
//       monto: '50000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Proveedores',
//       monto: '10000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Transferencias a Terceros',
//       monto: '1000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '06-01-2022 08:51 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Boleta de Garantia',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Pago de Previred',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Pago de Impuestos',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Remuneraciones',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 15:56 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Proveedores',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Transferencias a Terceros',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '03-01-2022 11:11 Hrs',
//       empresa: 'Inmobiliaria Velasco',
//       cuentaorigen: '236748967',
//       solucion: 'Transferencias entre Cuentas',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Hacktahon',
//       cuentaorigen: '223987454',
//       solucion: 'Boleta de Garantia',
//       monto: '6000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '01-02-2022 18:19 Hrs',
//       empresa: 'Inversiones Latinoamericanas',
//       cuentaorigen: '229435678',
//       solucion: 'Pago de Previred',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Supermercados Grupo 44',
//       cuentaorigen: '215364789',
//       solucion: 'Pago de Impuestos',
//       monto: '5000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'Universidades Americanas',
//       cuentaorigen: '362925378',
//       solucion: 'Pago de Tesoreria Gral. Republica',
//       monto: '23000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//     {
//       fecha: '02-01-2022 09:00 Hrs',
//       empresa: 'MegaHold Prime',
//       cuentaorigen: '210456783',
//       solucion: 'Pago de Remuneraciones',
//       monto: '10000000000',
//       estado: 'pendiente',
//       currencycode: 'CLP',
//     },
//   ],
// };

// console.log(transactions);
// export const dataset = transactions.data.forEach(function (obj) {
//   const postId = Math.random().toString(16).slice(2);
//   addDoc(collection(db, 'transaction'), {
//     id: postId,
//     date: obj.fecha,
//     company: obj.empresa,
//     origen: obj.cuentaorigen,
//     solution: obj.solucion,
//     amount: `${obj.currencycode} ${getFormatCurrency(
//       obj.monto,
//       obj.currencycode
//     )}`,
//     status: obj.estado,
//   })
//     .then(function (docRef) {
//       console.log('Document written with ID: ', docRef.id);
//     })
//     .catch(function (error) {
//       console.error('Error adding document: ', error);
//     });
// });

export { app, db, collection, onSnapshot };
